version: '3.8'

services:
  api:
    build: api
    ports:
      - "8000:8000"
    depends_on:
      - tarantool
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${TARANTOOL_USER_NAME}
      - DATABASE_PASSWORD=${TARANTOOL_USER_PASSWORD}
      - SECRET_KEY =${SECRET_KEY}
      - ALGORITHM =${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    volumes:
      - ./api:/app

  tarantool:
    image: tarantool/tarantool:2.10
    ports:
      - "3301:3301"
    volumes:
      - tarantool_data:/var/lib/tarantool
      - ./init.lua:/etc/tarantool/init.lua
    environment:
      - TARANTOOL_USER_NAME=${TARANTOOL_USER_NAME}
      - TARANTOOL_USER_PASSWORD=${TARANTOOL_USER_PASSWORD}
    command: >
      tarantool /etc/tarantool/init.lua

volumes:
  tarantool_data: